version: '3.5'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=
    volumes:
      - /var/lib/mariadb:/bitnami/mariadb
      - ./sql:/home/sql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  go:
    build: ./server
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend
      - app
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - app
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  client:
    build: ./client
    restart: always
    networks:
      - app

volumes:
  mariadb_data:
    driver: local

networks:
  backend:
    name: backend
  app:
    name: app

